### ISSUE TITLE
config.vbguest.auto_update = false

### ISSUE THREAD

**Issue by AnwarYagoub** [AnwarYagoub/RHCSA-RHCE-Lab-Environment#2]
@smartbit 

config.vbguest.auto_update = false

the above line from Vagrantfile works on if you have installed vagrant-vbguest plug-in for vagrant, so without this plug-in installed it will give the following error

``` shell
There are errors in the configuration of this machine. Please fix
the following errors and try again:

Vagrant:
* Unknown configuration section 'vbguest'.
```

if it is important we must add the command to install vagrant vbguest plug-in

``` shell
$ vagrant plugin install vagrant-vbguest
```

**Comment by smartbit** [comment]
try 

```
if defined? VagrantVbguest
      config.vbguest.auto_update = false 
end
```
