### ISSUE TITLE
I can't get it working

### ISSUE THREAD

**Issue by jmcalvar** [AnwarYagoub/RHCSA-RHCE-Lab-Environment#26]
I don't know which is the error. I'm reviewing the full Vagrantfile and I think everything is ok, but when I run Vagrant up:

Bringing machine 'cache-server' up with 'virtualbox' provider...
Bringing machine 'labipa' up with 'virtualbox' provider...
Bringing machine 'server1' up with 'virtualbox' provider...
Bringing machine 'server2' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible local provisioner:
* The following settings shouldn't exist: install_mode

**Comment by adaroobi** [comment]
What's your OS and Vagrant version?

**Comment by jmcalvar** [comment]
Hi,

I'm using Ubuntu 16.04 and Vagrant 1.8.1

**Comment by adaroobi** [comment]
Please consider upgrading your vagrant, at least to 1.8.7 or above. This issue have been resolved since then.
Take a look [Vagrant Changelog](https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#187-november-4-2016), upgrade and try again.
Hope this was helpful.

**Comment by jmcalvar** [comment]
Thank you very much
My mistake was that I tried to maintain the Ubuntu packages. I've downloaded vagrant from its website, and now it works, at least, I don't have ansible errors. Now I have other, but in vm, perhaps it is configuration. I'll investigate it

Jose
